openapi: 3.0.0
servers:
  - description: AutoNet REST API
    url: https://app.autonet.no/rest/v1
info:
  description: >
    API for accessing dealer data from AutoNet. This API uses token-based authentication. 
    To access any endpoint, clients must include a 'Token' header with the token found 
    [here](https://app.autonet.no/page/company) under the "API Access" tab.
  version: "1.0.0"
  title: AutoNet API
  contact:
    email: zk@autonet.no
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /ad/get:
    get:
      tags:
        - Ads
      summary: Get a list of all ads
      description: Returns a list of all car sale ads
      security:
        - TokenHeader: []
      responses:
        '200':
          description: A list of ads
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ad'
  /ad/get/{ID}:
     get:
      tags:
        - Ads
      summary: Get a specific ad
      description: Returns a specific car sale ad based on the provided ID
      security:
        - TokenHeader: []
      parameters:
        - name: ID
          in: path
          required: true
          description: Unique ID of the ad
          schema:
            type: integer
      responses:
        '200':
          description: A specific ad
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ad'
        '404':
          description: Ad not found
components:
  schemas:
    Ad:
      type: object
      properties:
        ads_id:
          type: integer
          format: int32
        sale_type:
          type: string
          enum:
            - USED_CAR
            - NEW_CAR
            - USED_MC
            - NEW_MC
            - MOBILEHOME
            - CARAVAN
            - TRAILER
            - BUS
            - LEASING
            - CAR_AUCTION
            - CAR_SUBSCRIPTION
        title:
          type: string
        description:
          type: string
          description: HTML based description
        contact_id:
          type: integer
          format: int32
        registration_price:
          type: integer
          format: int32
        total_price:
          type: integer
          format: int32
        preferences:
          $ref: '#/components/schemas/Preferences'
        address:
          $ref: '#/components/schemas/Address'
        creation_date_unix:
          type: integer
          format: int64
        update_date_unix:
          type: integer
          format: int64
        publish_date_unix:
          type: integer
          format: int64
        sold_date_unix:
          type: integer
          format: int64
        media:
          type: array
          items:
            $ref: '#/components/schemas/MediaItem'
      # Add other fields as necessary

    Preferences:
      type: object
      properties:
        hide_contact:
          type: boolean
          description: Contact person is available through API, but provider should hide
        hide_license:
          type: boolean
          description: License is available through API, but provider should hide
        hide_vin:
          type: boolean
          description: VIN is available through API, but provider should hide
        tradein_accepted:
          type: boolean
          description: Primarily used in AutoNet's www service to stop visitors from sending tradein-requests

    Address:
      type: object
      properties:
        id:
          type: integer
          format: int32
        type:
          type: string
          description: What kind of address it is
          enum:
            - VISITING
            - INVOICING
            - POSTAL
        address:
          type: string
        postal_code:
          type: integer
          format: int32
        city:
          type: string
        country:
          type: string
        status:
          type: string
          description: The status of the address
          enum:
            - ACTIVE
            - DEACTIVATED
          
    MediaItem:
      type: object
      properties:
        id:
            type: integer
            format: int32
        priority:
            type: integer
            format: int32
            description: Position of image, 0 is first
        url:
            type: string
            description: Full URI to AWS-auth
        description:
            type: string
            description: User-set description
        date_unix:
            type: integer
            format: int64
        background_removed:
            type: boolean
            description: If AutoNet's removebackground service has been applied
        logo_background:
            type: boolean
            description: If AutoNet's logobackground service has been applied
  securitySchemes:
    TokenHeader:
      type: apiKey
      in: header
      name: Token
security:
  - TokenHeader: []
